name: rentworthy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  logger: ^2.0.1
  page_transition: ^2.0.9
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  permission_handler: ^10.4.3
  path_provider: ^2.1.0
  device_preview: ^1.1.0
  smooth_page_indicator: ^1.1.0
  animations: ^2.0.7
  flutter_animate: ^4.2.0+1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  gradient_borders: ^1.0.0
  percent_indicator: ^4.2.3
  readmore: ^2.2.0
  emoji_picker_flutter: ^1.6.1
  we_slide: ^2.4.0
  flutter_rating_bar: ^4.0.1
  #  dropdown_search: ^5.0.6
  dio: ^5.3.2
  syncfusion_flutter_sliders: ^22.2.11
  #  pinput: ^3.0.0
  pin_code_fields: ^8.0.1
  syncfusion_flutter_datepicker: ^22.2.11
  persistent_bottom_nav_bar: ^5.0.2
  table_calendar: ^3.0.9
#  smart_auth: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/applogo.png"
  image_dark: "assets/images/applogo.png"
  color_dark: "#FFFFFF"

  android_12:
    color: "#FFFFFF"

  android_disable_fullscreen: true
  android: true
  ios: true
  fullscreen: true


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

